name: ripple_effect
description: An easy way to start a ripple effect from any widget to the entire screen on your flutter app.
version: 0.1.2
homepage: https://github.com/ericdallo/ripple_effect

environment:
  sdk: ">=2.14.4 <3.0.0"
  flutter: ">= 2.5.3"

dependencies:
  flutter:
    sdk: flutter
  rect_getter: ^1.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
